# Check duplicate tweets

In [1]:
import pandas as pd

In [5]:
%%sh
pwd
ls ../../data

/Users/melissacirtain/work/NLP_on_Social_Media_Data/src/melissa
#chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.json
#chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.tsv
#tyrenichols_project_tweets.2023-03-09_19.25.43.435891.json
#tyrenichols_project_tweets.2023-03-09_19.25.43.435891.tsv
anu_annotations.tsv
chatgpt_project_tweets.2023-03-09_19.12.39.616553.json
chatgpt_project_tweets.2023-03-09_19.12.39.616553.tsv
deduplicated_tweets.2023-03-26_14.08.48.636120.tsv
maga_project_tweets.2023-03-08_22.25.11.437694.json
maga_project_tweets.2023-03-08_22.25.11.437694.tsv
mel_annotations.csv
mel_annotations.tsv
obama_project_tweets.2023-03-08_22.36.15.226664.json
obama_project_tweets.2023-03-08_22.36.15.226664.tsv
project_data.2023-03-11_13.11.55.783862.csv
project_data.2023-03-11_13.11.55.783862.json
russia_project_tweets.2023-03-08_22.51.51.710826.json
russia_project_tweets.2023-03-08_22.51.51.710826.tsv
sarik_annotations.tsv
scraped_data
statehood_project_tweets.2023-03-09_17.12.00.547177.json
statehood_project_tweets.2023-03-09_17.12.00.547177.tsv
textblob_polarity.2023-03-26_14.35.07.210250.tsv
ukraine_project_tweets.2023-03-09_12.09.04.774701.json
ukraine_project_tweets.2023-03-09_12.09.04.774701.tsv
vader_polarity.2023-03-26_14.38.52.858509.tsv

In [7]:
datafile = '../../data/deduplicated_tweets.2023-03-26_14.08.48.636120.tsv'
df = pd.read_csv(datafile, sep='\t')
df.head(3)

,Unnamed: 0,conversation_id,lang,reply_settings,created_at,clean_text,text,author_id,referenced_tweets,id,...,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.impression_count,in_reply_to_user_id,geo.place_id,withheld.copyright,withheld.country_codes,geo.coordinates.type,geo.coordinates.coordinates
0,0,1633954063934009344,en,everyone,2023-03-09 22:13:00+00:00,rt infantry bucky lucky chrisrocklive worse th...,RT @Infantry_bucky: He’s lucky a #ChrisRockLiv...,1519164980582653952,"[{'type': 'retweeted', 'id': '1633938373529292...",1633954063934009344,...,8,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1633954058212876288,en,everyone,2023-03-09 22:12:59+00:00,rt ofakindnocap chris rock cheated never perso...,RT @1_ofakindnocap: Chris Rock: “we all been c...,21575184,"[{'type': 'retweeted', 'id': '1632283297588948...",1633954058212876288,...,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1633951267423768576,en,everyone,2023-03-09 22:01:54+00:00,rt ofakindnocap chris rock cheated never perso...,RT @1_ofakindnocap: Chris Rock: “we all been c...,360633018,"[{'type': 'retweeted', 'id': '1632283297588948...",1633951267423768576,...,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(df.shape)

(32291, 21)

In [9]:
df['conversation_id'].nunique()

30611

# Check new dedup file
- Looks good!

In [13]:
new_datafile = '../../data/deduplicated_tweets_by_conversation_id_.2023-04-01_16.15.21.235875.tsv'
new_df = pd.read_csv(new_datafile, delimiter='\t')
print(new_df.shape)
assert new_df['conversation_id'].nunique() == new_df.shape[0]

(30611, 21)

### How many of each type of tweet?

In [14]:
print(new_df.columns)
new_df.head(3)

Index(['Unnamed: 0', 'conversation_id', 'lang', 'reply_settings', 'created_at',
       'clean_text', 'text', 'author_id', 'referenced_tweets', 'id',
       'edit_history_tweet_ids', 'public_metrics.retweet_count',
       'public_metrics.reply_count', 'public_metrics.like_count',
       'public_metrics.impression_count', 'in_reply_to_user_id',
       'geo.place_id', 'withheld.copyright', 'withheld.country_codes',
       'geo.coordinates.type', 'geo.coordinates.coordinates'],
      dtype='object')

,Unnamed: 0,conversation_id,lang,reply_settings,created_at,clean_text,text,author_id,referenced_tweets,id,...,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.impression_count,in_reply_to_user_id,geo.place_id,withheld.copyright,withheld.country_codes,geo.coordinates.type,geo.coordinates.coordinates
0,0,1633954063934009344,en,everyone,2023-03-09 22:13:00+00:00,rt infantry bucky lucky chrisrocklive worse th...,RT @Infantry_bucky: He’s lucky a #ChrisRockLiv...,1519164980582653952,"[{'type': 'retweeted', 'id': '1633938373529292...",1633954063934009344,...,8,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1633954058212876288,en,everyone,2023-03-09 22:12:59+00:00,rt ofakindnocap chris rock cheated never perso...,RT @1_ofakindnocap: Chris Rock: “we all been c...,21575184,"[{'type': 'retweeted', 'id': '1632283297588948...",1633954058212876288,...,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1633951267423768576,en,everyone,2023-03-09 22:01:54+00:00,rt ofakindnocap chris rock cheated never perso...,RT @1_ofakindnocap: Chris Rock: “we all been c...,360633018,"[{'type': 'retweeted', 'id': '1632283297588948...",1633951267423768576,...,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN