# Twittter Data ETL

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
# import seaborn as sns
from datetime import datetime

In [8]:
!pwd
!ls -l ../../data

/Users/melissacirtain/work/NLP_on_Social_Media_Data/src/melissa
total 158280
-rw-r--r--  1 melissacirtain  staff   2478135 Mar  9 17:24 #chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.json
-rw-r--r--  1 melissacirtain  staff   1699708 Mar  9 17:24 #chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.tsv
-rw-r--r--  1 melissacirtain  staff   2469582 Mar 11 12:12 #tyrenichols_project_tweets.2023-03-09_19.25.43.435891.json
-rw-r--r--  1 melissacirtain  staff   1697993 Mar 11 12:12 #tyrenichols_project_tweets.2023-03-09_19.25.43.435891.tsv
-rw-r--r--  1 melissacirtain  staff   2426782 Mar 11 12:12 chatgpt_project_tweets.2023-03-09_19.12.39.616553.json
-rw-r--r--  1 melissacirtain  staff   1646638 Mar 11 12:12 chatgpt_project_tweets.2023-03-09_19.12.39.616553.tsv
-rw-r--r--  1 melissacirtain  staff    511146 Mar  9 17:23 maga_project_tweets.2023-03-08_22.25.11.437694.json
-rw-r--r--  1 melissacirtain  staff    381596 Mar  9 17:23 maga_project_tweets.2023-03-08_22.25.11.437694.tsv
-rw-r--r--  1 melissacirtain  staff   2374880 Mar  9 17:23 obama_project_tweets.2023-03-08_22.36.15.226664.json
-rw-r--r--  1 melissacirtain  staff   1724693 Mar  9 17:23 obama_project_tweets.2023-03-08_22.36.15.226664.tsv
-rw-r--r--  1 melissacirtain  staff  14405477 Mar  9 18:49 project_data.2023-03-09_18.49.52.391752.json
-rw-r--r--  1 melissacirtain  staff  36406862 Mar 11 12:38 project_data.2023-03-11_12.38.08.724882.json
-rw-r--r--  1 melissacirtain  staff   2538150 Mar  9 18:10 russia_project_tweets.2023-03-08_22.51.51.710826.json
-rw-r--r--  1 melissacirtain  staff   1773671 Mar  9 17:34 russia_project_tweets.2023-03-08_22.51.51.710826.tsv
-rw-r--r--  1 melissacirtain  staff   2522407 Mar  9 17:24 statehood_project_tweets.2023-03-09_17.12.00.547177.json
-rw-r--r--  1 melissacirtain  staff   1762648 Mar  9 17:24 statehood_project_tweets.2023-03-09_17.12.00.547177.tsv
-rw-r--r--  1 melissacirtain  staff   2473304 Mar  9 18:10 ukraine_project_tweets.2023-03-09_12.09.04.774701.json
-rw-r--r--  1 melissacirtain  staff   1711914 Mar  9 18:10 ukraine_project_tweets.2023-03-09_12.09.04.774701.tsv

# Merge data

In [16]:
# Gather input files
json_files = !ls ../../data/*.json
print(json_files)

# Get columns
tmp = pd.read_json(json_files[0])
columns = list(tmp.columns)
columns.append('keyword')

# Combine all datasets
df = pd.DataFrame(columns=columns)
for f in json_files:
    tmp = pd.read_json(f)
    tmp['keyword'] = f.split('data/')[1].split('_project_tweets')[0]
    df = df.append(tmp)
    print(df.shape)

# Inspect data
df.reset_index(inplace=True, drop=True)
display(df.head())
display(df.tail())

# Save combinied dataset
timestamp = str(datetime.now()).replace(' ', '_').replace(':', '.')
print(timestamp)

outpath = os.path.join('..', '..', 'data', f'project_data.{timestamp}.json')
df.to_json(outpath)
print(f'Wrote full dataset to {outpath}')

# csv version:
csv_outpath = os.path.join('..', '..', 'data', f'project_data.{timestamp}.csv')
df.to_csv(csv_outpath, )
print(f'Wrote full dataset to {csv_outpath}')

['../../data/#chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.json', '../../data/#tyrenichols_project_tweets.2023-03-09_19.25.43.435891.json', '../../data/chatgpt_project_tweets.2023-03-09_19.12.39.616553.json', '../../data/maga_project_tweets.2023-03-08_22.25.11.437694.json', '../../data/obama_project_tweets.2023-03-08_22.36.15.226664.json', '../../data/russia_project_tweets.2023-03-08_22.51.51.710826.json', '../../data/statehood_project_tweets.2023-03-09_17.12.00.547177.json', '../../data/ukraine_project_tweets.2023-03-09_12.09.04.774701.json']
(5070, 19)
(10108, 19)
(15200, 21)
(16299, 21)
(21388, 21)
(26487, 21)
(31581, 21)
(36581, 21)

,conversation_id,lang,reply_settings,created_at,text,author_id,referenced_tweets,id,edit_history_tweet_ids,public_metrics.retweet_count,...,public_metrics.like_count,public_metrics.quote_count,public_metrics.impression_count,in_reply_to_user_id,geo.place_id,withheld.copyright,withheld.country_codes,keyword,geo.coordinates.type,geo.coordinates.coordinates
0,1633954063934009344,en,everyone,2023-03-09 22:13:00+00:00,RT @Infantry_bucky: He’s lucky a #ChrisRockLiv...,1519164980582653952,"[{'type': 'retweeted', 'id': '1633938373529292...",1633954063934009344,[1633954063934009354],8,...,0,0,0,NaN,None,NaN,None,#chrisrocklive,NaN,NaN
1,1633954058212876288,en,everyone,2023-03-09 22:12:59+00:00,RT @1_ofakindnocap: Chris Rock: “we all been c...,21575184,"[{'type': 'retweeted', 'id': '1632283297588948...",1633954058212876288,[1633954058212876289],616,...,0,0,0,NaN,None,NaN,None,#chrisrocklive,NaN,NaN
2,1633951267423768576,en,everyone,2023-03-09 22:01:54+00:00,RT @1_ofakindnocap: Chris Rock: “we all been c...,360633018,"[{'type': 'retweeted', 'id': '1632283297588948...",1633951267423768576,[1633951267423768578],616,...,0,0,0,NaN,None,NaN,None,#chrisrocklive,NaN,NaN
3,1633950853626318848,en,everyone,2023-03-09 22:00:15+00:00,RT @rolandsmartin: Working out and watching th...,1547101103803830272,"[{'type': 'retweeted', 'id': '1632825595473149...",1633950853626318848,[1633950853626318850],14,...,0,0,0,NaN,None,NaN,None,#chrisrocklive,NaN,NaN
4,1633950824664645632,en,everyone,2023-03-09 22:00:08+00:00,RT @rolandsmartin: Workout done. I’ll have a f...,1547101103803830272,"[{'type': 'retweeted', 'id': '1632833853021728...",1633950824664645632,[1633950824664645634],8,...,0,0,0,NaN,None,NaN,None,#chrisrocklive,NaN,NaN

,conversation_id,lang,reply_settings,created_at,text,author_id,referenced_tweets,id,edit_history_tweet_ids,public_metrics.retweet_count,...,public_metrics.like_count,public_metrics.quote_count,public_metrics.impression_count,in_reply_to_user_id,geo.place_id,withheld.copyright,withheld.country_codes,keyword,geo.coordinates.type,geo.coordinates.coordinates
36576,1633873450594091008,en,everyone,2023-03-09 16:52:41+00:00,RT @MinisterBoomer: On the way to @SusanneM090...,1364374610922323968,"[{'type': 'retweeted', 'id': '1633019489641017...",1633873450594091008,[1633873450594091015],14,...,0,0,0,NaN,None,NaN,None,ukraine,NaN,NaN
36577,1633873450422140928,en,everyone,2023-03-09 16:52:41+00:00,"#Russia 🇷🇺 / #Ukraine 🇺🇦 / #Belarus 🇧🇾\n\n🔴 ""T...",985264069816061952,None,1633873450422140928,[1633873450422140928],1,...,4,0,142,NaN,None,NaN,None,ukraine,NaN,NaN
36578,1633873447897149440,en,everyone,2023-03-09 16:52:40+00:00,RT @kajakallas: 79 years ago Soviet planes bom...,1250015178248290304,"[{'type': 'retweeted', 'id': '1633741101885542...",1633873447897149440,[1633873447897149444],1305,...,0,0,0,NaN,None,NaN,None,ukraine,NaN,NaN
36579,1633873447108632576,en,everyone,2023-03-09 16:52:40+00:00,RT @sternenko: Today 4 civilians were killed b...,1495109228876468224,"[{'type': 'retweeted', 'id': '1633803881447604...",1633873447108632576,[1633873447108632576],1541,...,0,0,0,NaN,None,NaN,None,ukraine,NaN,NaN
36580,1633873445154091008,en,everyone,2023-03-09 16:52:39+00:00,RT @Sunshinelove68: 💥How Did the U.S. Lose Six...,980084548376584192,"[{'type': 'retweeted', 'id': '1633861161144958...",1633873445154091008,[1633873445154091008],2,...,0,0,0,NaN,None,NaN,None,ukraine,NaN,NaN

2023-03-11_13.11.55.783862
Wrote full dataset to ../../data/project_data.2023-03-11_13.11.55.783862.json
Wrote full dataset to ../../data/project_data.2023-03-11_13.11.55.783862.csv

# Check for uniqueness
Sarik identified that there were some duplicated tweets in the data.  Explore where those are and mitigate.

In [17]:
print(df.shape)
df.columns

(36581, 21)

Index(['conversation_id', 'lang', 'reply_settings', 'created_at', 'text',
       'author_id', 'referenced_tweets', 'id', 'edit_history_tweet_ids',
       'public_metrics.retweet_count', 'public_metrics.reply_count',
       'public_metrics.like_count', 'public_metrics.quote_count',
       'public_metrics.impression_count', 'in_reply_to_user_id',
       'geo.place_id', 'withheld.copyright', 'withheld.country_codes',
       'keyword', 'geo.coordinates.type', 'geo.coordinates.coordinates'],
      dtype='object')

In [18]:
df['conversation_id'].nunique()

30611

In [19]:
df['id'].nunique()

32275

# Duplication
Did one of the datasets get messed up?  We have some duplicate rows. Are they isolated to a single dataset, or are they spread out?  Either way, we need to deduplicate the data.

- Melissa:  maga, statehood, #chrisrocklive, 
- Sarik: tyre, chatgpt, russia, ukraine. 
- (5000 each, no time limits)

- the **#tyrenichols** dataset and the **maga** dataset seem to have mostly duplicate tweets.  Not sure why this would be.  We should investigate if there are edits or some other reason they don't have unique tweets near 100%.

In [46]:
import string

my_keywords = list(df['keyword'].unique())
print(f'My keywords: {my_keywords}\n')

col_width = 15

for kw in my_keywords:
    unique_for_kw = df.loc[df['keyword'] == kw]['conversation_id'].nunique()
    rows_for_kw = df.loc[df['keyword'] == kw].shape[0]
    my_pct = round(100.0*unique_for_kw/rows_for_kw, 2)
    print(f'{kw.ljust(15)} {str(my_pct).ljust(15)} {unique_for_kw}/{rows_for_kw} ')

My keywords: ['#chrisrocklive', '#tyrenichols', 'chatgpt', 'maga', 'obama', 'russia', 'statehood', 'ukraine']

#chrisrocklive  99.74           5057/5070
#tyrenichols    14.77           744/5038
chatgpt         96.48           4913/5092
maga            96.18           1057/1099
obama           93.44           4755/5089
russia          93.29           4757/5099
statehood       92.78           4726/5094
ukraine         96.06           4803/5000