In [1]:
import pandas as pd

In [4]:
!ls ../../data
datafile = '../../data/deduplicated_tweets.2023-03-26_14.08.48.636120.tsv'
df = pd.read_csv(datafile, sep='\t')
df.head()

#chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.json
#chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.tsv
#tyrenichols_project_tweets.2023-03-09_19.25.43.435891.json
#tyrenichols_project_tweets.2023-03-09_19.25.43.435891.tsv
chatgpt_project_tweets.2023-03-09_19.12.39.616553.json
chatgpt_project_tweets.2023-03-09_19.12.39.616553.tsv
deduplicated_tweets.2023-03-26_14.08.48.636120.tsv
maga_project_tweets.2023-03-08_22.25.11.437694.json
maga_project_tweets.2023-03-08_22.25.11.437694.tsv
obama_project_tweets.2023-03-08_22.36.15.226664.json
obama_project_tweets.2023-03-08_22.36.15.226664.tsv
project_data.2023-03-11_13.11.55.783862.csv
project_data.2023-03-11_13.11.55.783862.json
russia_project_tweets.2023-03-08_22.51.51.710826.json
russia_project_tweets.2023-03-08_22.51.51.710826.tsv
scraped_data
statehood_project_tweets.2023-03-09_17.12.00.547177.json
statehood_project_tweets.2023-03-09_17.12.00.547177.tsv
textblob_polarity.2023-03-26_14.35.07.210250.tsv
ukraine_project_tweets.2023-03-09_12.09.04.774701.json
ukraine_project_tweets.2023-03-09_12.09.04.774701.tsv
vader_polarity.2023-03-26_14.38.52.858509.tsv

,Unnamed: 0,conversation_id,lang,reply_settings,created_at,clean_text,text,author_id,referenced_tweets,id,...,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.impression_count,in_reply_to_user_id,geo.place_id,withheld.copyright,withheld.country_codes,geo.coordinates.type,geo.coordinates.coordinates
0,0,1633954063934009344,en,everyone,2023-03-09 22:13:00+00:00,rt infantry bucky lucky chrisrocklive worse th...,RT @Infantry_bucky: He’s lucky a #ChrisRockLiv...,1519164980582653952,"[{'type': 'retweeted', 'id': '1633938373529292...",1633954063934009344,...,8,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1633954058212876288,en,everyone,2023-03-09 22:12:59+00:00,rt ofakindnocap chris rock cheated never perso...,RT @1_ofakindnocap: Chris Rock: “we all been c...,21575184,"[{'type': 'retweeted', 'id': '1632283297588948...",1633954058212876288,...,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1633951267423768576,en,everyone,2023-03-09 22:01:54+00:00,rt ofakindnocap chris rock cheated never perso...,RT @1_ofakindnocap: Chris Rock: “we all been c...,360633018,"[{'type': 'retweeted', 'id': '1632283297588948...",1633951267423768576,...,616,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1633950853626318848,en,everyone,2023-03-09 22:00:15+00:00,rt rolandsmartin working watching chrisrock ne...,RT @rolandsmartin: Working out and watching th...,1547101103803830272,"[{'type': 'retweeted', 'id': '1632825595473149...",1633950853626318848,...,14,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1633950824664645632,en,everyone,2023-03-09 22:00:08+00:00,rt rolandsmartin workout done comment chrisroc...,RT @rolandsmartin: Workout done. I’ll have a f...,1547101103803830272,"[{'type': 'retweeted', 'id': '1632833853021728...",1633950824664645632,...,8,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
annotation_df = df.sample(n=300)
annotation_df['our_label'] = ""
display(annotation_df.head())
mel_df = annotation_df[:100]
mel_df.shape

anu_df = annotation_df[100:200]
sarik_df = annotation_df[200:]
print(mel_df.shape, anu_df.shape, sarik_df.shape)

mel_df.to_csv('../../data/mel_annotations.tsv')
anu_df.to_csv('../../data/anu_annotations.tsv')
sarik_df.to_csv('../../data/sarik_annotations.tsv')

,Unnamed: 0,conversation_id,lang,reply_settings,created_at,clean_text,text,author_id,referenced_tweets,id,...,public_metrics.reply_count,public_metrics.like_count,public_metrics.impression_count,in_reply_to_user_id,geo.place_id,withheld.copyright,withheld.country_codes,geo.coordinates.type,geo.coordinates.coordinates,our_label
13581,17871,1633665111406542848,en,everyone,2023-03-09 03:04:49+00:00,rt tomfitton obama knew clinton knew biden kne...,RT @TomFitton: Obama knew. Clinton knew. Biden...,3024401194,"[{'type': 'retweeted', 'id': '1633625411845345...",1633665111406542848,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,
13249,17539,1633666519245750272,en,everyone,2023-03-09 03:10:24+00:00,cant even threaten friend game without watchli...,cant even threaten my friends during a game wi...,1579224008033275904,"[{'type': 'quoted', 'id': '1633098341578940417'}]",1633666519245750272,...,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,
28682,32972,1633876284940877824,en,everyone,2023-03-09 17:03:56+00:00,trump impeached call gop house brought article...,Trump was impeached over a ☎️ call! Why has th...,200698213,NaN,1633876284940877824,...,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,
1203,1203,1633277949234364416,en,everyone,2023-03-08 01:26:22+00:00,rt sagesurge marlon wayans roasting chris rock...,RT @sagesurge: Marlon Wayans roasting Chris Ro...,1093689222823849984,"[{'type': 'retweeted', 'id': '1632525319973289...",1633277949234364416,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,
22163,26453,1633668541122592768,en,everyone,2023-03-09 03:18:26+00:00,rt visegrad time west send patriot missile def...,RT @visegrad24: It’s time for the West to send...,4060962981,"[{'type': 'retweeted', 'id': '1633639497408696...",1633668541122592768,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,

(100, 22) (100, 22) (100, 22)

In [12]:
ls ../../data/

#chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.json
#chrisrocklive_project_tweets.2023-03-09_17.16.18.676751.tsv
#tyrenichols_project_tweets.2023-03-09_19.25.43.435891.json
#tyrenichols_project_tweets.2023-03-09_19.25.43.435891.tsv
anu_annotations.tsv
chatgpt_project_tweets.2023-03-09_19.12.39.616553.json
chatgpt_project_tweets.2023-03-09_19.12.39.616553.tsv
deduplicated_tweets.2023-03-26_14.08.48.636120.tsv
maga_project_tweets.2023-03-08_22.25.11.437694.json
maga_project_tweets.2023-03-08_22.25.11.437694.tsv
mel_annotations.tsv
obama_project_tweets.2023-03-08_22.36.15.226664.json
obama_project_tweets.2023-03-08_22.36.15.226664.tsv
project_data.2023-03-11_13.11.55.783862.csv
project_data.2023-03-11_13.11.55.783862.json
russia_project_tweets.2023-03-08_22.51.51.710826.json
russia_project_tweets.2023-03-08_22.51.51.710826.tsv
sarik_annotations.tsv
scraped_data/
statehood_project_tweets.2023-03-09_17.12.00.547177.json
statehood_project_tweets.2023-03-09_17.12.00.547177.tsv
textblob_polarity.2023-03-26_14.35.07.210250.tsv
ukraine_project_tweets.2023-03-09_12.09.04.774701.json
ukraine_project_tweets.2023-03-09_12.09.04.774701.tsv
vader_polarity.2023-03-26_14.38.52.858509.tsv

# Melissa Annotations

In [15]:
# mel_df.to_csv('../../data/mel_annotations.csv')  # I made a .csv that was easier to open in excel
# Did my annotations there.
# Convert back to .tsv format to match the others.

mel_annotated_df = pd.read_csv('../../data/mel_annotations.csv')
mel_annotated_df.head()

,Unnamed: 0,Unnamed: 0.1,conversation_id,lang,reply_settings,created_at,clean_text,text,author_id,referenced_tweets,...,public_metrics.reply_count,public_metrics.like_count,public_metrics.impression_count,in_reply_to_user_id,geo.place_id,withheld.copyright,withheld.country_codes,geo.coordinates.type,geo.coordinates.coordinates,our_label
0,13581,17871,1.633670e+18,en,everyone,2023-03-09 03:04:49+00:00,rt tomfitton obama knew clinton knew biden kne...,RT @TomFitton: Obama knew. Clinton knew. Biden...,3.024401e+09,"[{'type': 'retweeted', 'id': '1633625411845345...",...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,neutral
1,13249,17539,1.633670e+18,en,everyone,2023-03-09 03:10:24+00:00,cant even threaten friend game without watchli...,cant even threaten my friends during a game wi...,1.579220e+18,"[{'type': 'quoted', 'id': '1633098341578940417'}]",...,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,negative
2,28682,32972,1.633880e+18,en,everyone,2023-03-09 17:03:56+00:00,trump impeached call gop house brought article...,Trump was impeached over a ☎️ call! Why has th...,2.006982e+08,NaN,...,0,0,15,NaN,NaN,NaN,NaN,NaN,NaN,negative
3,1203,1203,1.633280e+18,en,everyone,2023-03-08 01:26:22+00:00,rt sagesurge marlon wayans roasting chris rock...,RT @sagesurge: Marlon Wayans roasting Chris Ro...,1.093690e+18,"[{'type': 'retweeted', 'id': '1632525319973289...",...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,neutral
4,22163,26453,1.633670e+18,en,everyone,2023-03-09 03:18:26+00:00,rt visegrad time west send patriot missile def...,RT @visegrad24: It’s time for the West to send...,4.060963e+09,"[{'type': 'retweeted', 'id': '1633639497408696...",...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,neutral

In [16]:
mel_annotated_df['our_label'].value_counts()

neutral     57
negative    34
positive     9
Name: our_label, dtype: int64

In [17]:
mel_annotated_df.to_csv('../../data/mel_annotations.tsv', sep='\t')